
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  superadmin: [PERMISSIONS.FULL_ACCESS],

  vendor_admin: [
    PERMISSIONS.VERIFY_VENDORS,
    PERMISSIONS.MANAGE_VENDORS,
  ],
  product_admin: [
    PERMISSIONS.APPROVE_PRODUCTS,
    PERMISSIONS.CREATE_CATEGORIES,
    PERMISSIONS.EDIT_CATEGORIES,
    PERMISSIONS.FLAG_ITEMS,
  ],
  warehouse_admin: [
    PERMISSIONS.VET_PRODUCTS,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.TRACK_STOCK,
  ],
  dispatch_admin: [
    PERMISSIONS.MANAGE_DISPATCH,
    PERMISSIONS.TRACK_SHIPMENTS,
  ],
  dispute_admin: [
    PERMISSIONS.RESOLVE_DISPUTES,
    PERMISSIONS.ISSUE_REFUNDS,
  ],
  finance_admin: [
    PERMISSIONS.VIEW_TRANSACTIONS,
    PERMISSIONS.PROCESS_REFUNDS,
    PERMISSIONS.PAY_VENDORS,
  ],
  support_admin: [
    PERMISSIONS.RESPOND_TICKETS,
    PERMISSIONS.ESCALATE_ISSUES,
  ],
  marketing_admin: [
    PERMISSIONS.CREATE_CAMPAIGNS,
    PERMISSIONS.MANAGE_ADS,
    PERMISSIONS.EDIT_BANNERS,
  ],
  analytics_admin: [
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_DATA,
  ],
  compliance_admin: [
    PERMISSIONS.AUDIT_LOGS,
    PERMISSIONS.FLAG_FRAUD,
    PERMISSIONS.VERIFY_DOCUMENTS,
  ],
  content_admin: [
    PERMISSIONS.EDIT_CONTENT,
    PERMISSIONS.MANAGE_BLOG,
    PERMISSIONS.OPTIMIZE_SEO,
  ],
  review_moderator: [
    PERMISSIONS.MODERATE_REVIEWS,
    PERMISSIONS.BAN_USERS,
  ],
  tech_admin: [
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.DEPLOY_UPDATES,
  ],
};
