// Helper function to get preferences based on country name
export default function getCountryPreferences(countryName: string): { language: string; currency: string; country: string } {
    // Default preferences
    const defaults = { language: "en", currency: "USD", country: countryName || "United States" };
    
    // Map of country names to their preferences
    const countryPreferences: Record<string, { language: string; currency: string; country: string }> = {
      "Afghanistan": { language: "fa", currency: "AFN", country: "Afghanistan" },
      "Albania": { language: "sq", currency: "ALL", country: "Albania" },
      "Algeria": { language: "ar", currency: "DZD", country: "Algeria" },
      "Andorra": { language: "ca", currency: "EUR", country: "Andorra" },
      "Angola": { language: "pt", currency: "AOA", country: "Angola" },
      "Antiqua and Barbuda": { language: "en", currency: "XCD", country: "Antigua and Barbuda" },
      "Argentina": { language: "es", currency: "ARS", country: "Argentina" },
      "Armenia": { language: "hy", currency: "AMD", country: "Armenia" },
      "Australia": { language: "en", currency: "AUD", country: "Australia" },
      "Austria": { language: "de", currency: "EUR", country: "Austria" },
      "Azerbaijan": { language: "az", currency: "AZN", country: "Azerbaijan" },
      "Bahamas": { language: "en", currency: "BSD", country: "Bahamas" },
      "Bahrain": { language: "ar", currency: "BHD", country: "Bahrain" },
      "Bangladesh": { language: "bn", currency: "BDT", country: "Bangladesh" },
      "Barbados": { language: "en", currency: "BBD", country: "Barbados" },
      "Belarus": { language: "be", currency: "BYN", country: "Belarus" },
      "Belgium": { language: "fr", currency: "EUR", country: "Belgium" },
      "Belize": { language: "en", currency: "BZD", country: "Belize" },
      "Benin": { language: "fr", currency: "XOF", country: "Benin" },
      "Bhutan": { language: "dz", currency: "BTN", country: "Bhutan" },
      "Bolivia": { language: "es", currency: "BOB", country: "Bolivia" },
      "Bosnia and Herzegovina": { language: "bs", currency: "BAM", country: "Bosnia and Herzegovina" },
      "Botswana": { language: "en", currency: "BWP", country: "Botswana" },
      "Brazil": { language: "pt", currency: "BRL", country: "Brazil" },
      "Brunei": { language: "ms", currency: "BND", country: "Brunei" },
      "Bulgaria": { language: "bg", currency: "BGN", country: "Bulgaria" },
      "Burkina Faso": { language: "fr", currency: "XOF", country: "Burkina Faso" },
      "Burundi": { language: "fr", currency: "BIF", country: "Burundi" },
      "Cabo Verde": { language: "pt", currency: "CVE", country: "Cabo Verde" },
      "Cambodia": { language: "km", currency: "KHR", country: "Cambodia" },
      "Cameroon": { language: "fr", currency: "XAF", country: "Cameroon" },
      "Canada": { language: "en", currency: "CAD", country: "Canada" },
      "Central African Republic": { language: "fr", currency: "XAF", country: "Central African Republic" },
      "Chad": { language: "fr", currency: "XAF", country: "Chad" },
      "Chile": { language: "es", currency: "CLP", country: "Chile" },
      "China": { language: "zh", currency: "CNY", country: "China" },
      "Colombia": { language: "es", currency: "COP", country: "Colombia" },
      "Comoros": { language: "ar", currency: "KMF", country: "Comoros" },
      "Congo (Congo-Brazzaville)": { language: "fr", currency: "XAF", country: "Congo" },
      "Congo (Congo-Kinshasa)": { language: "fr", currency: "CDF", country: "Democratic Republic of the Congo" },
      "Costa Rica": { language: "es", currency: "CRC", country: "Costa Rica" },
      "Croatia": { language: "hr", currency: "EUR", country: "Croatia" },
      "Cuba": { language: "es", currency: "CUP", country: "Cuba" },
      "Cyprus": { language: "el", currency: "EUR", country: "Cyprus" },
      "Czech Republic": { language: "cs", currency: "CZK", country: "Czech Republic" },
      "Denmark": { language: "da", currency: "DKK", country: "Denmark" },
      "Djibouti": { language: "fr", currency: "DJF", country: "Djibouti" },
      "Dominica": { language: "en", currency: "XCD", country: "Dominica" },
      "Dominican Republic": { language: "es", currency: "DOP", country: "Dominican Republic" },
      "Ecuador": { language: "es", currency: "USD", country: "Ecuador" },
      "Egypt": { language: "ar", currency: "EGP", country: "Egypt" },
      "Equatorial Guinea": { language: "es", currency: "XAF", country: "Equatorial Guinea" },
      "Eritrea": { language: "ti", currency: "ERN", country: "Eritrea" },
      "Estonia": { language: "et", currency: "EUR", country: "Estonia" },
      "Eswatini": { language: "en", currency: "SZL", country: "Eswatini" },
      "El Salvador": { language: "es", currency: "USD", country: "El Salvador" },
      "Ethiopia": { language: "am", currency: "ETB", country: "Ethiopia" },
      "Fiji": { language: "en", currency: "FJD", country: "Fiji" },
      "Finland": { language: "fi", currency: "EUR", country: "Finland" },
      "France": { language: "fr", currency: "EUR", country: "France" },
      "Gabon": { language: "fr", currency: "XAF", country: "Gabon" },
      "Gambia": { language: "en", currency: "GMD", country: "Gambia" },
      "Georgia": { language: "ka", currency: "GEL", country: "Georgia" },
      "Germany": { language: "de", currency: "EUR", country: "Germany" },
      "Ghana": { language: "en", currency: "GHS", country: "Ghana" },
      "Greece": { language: "el", currency: "EUR", country: "Greece" },
      "Grenada": { language: "en", currency: "XCD", country: "Grenada" },
      "Guatemala": { language: "es", currency: "GTQ", country: "Guatemala" },
      "Guinea": { language: "fr", currency: "GNF", country: "Guinea" },
      "Guinea-Bissau": { language: "pt", currency: "XOF", country: "Guinea-Bissau" },
      "Guyana": { language: "en", currency: "GYD", country: "Guyana" },
      "Haiti": { language: "fr", currency: "HTG", country: "Haiti" },
      "Honduras": { language: "es", currency: "HNL", country: "Honduras" },
      "Hong Kong": { language: "zh", currency: "HKD", country: "Hong Kong" },
      "Hungary": { language: "hu", currency: "HUF", country: "Hungary" },
      "Iceland": { language: "is", currency: "ISK", country: "Iceland" },
      "India": { language: "en", currency: "INR", country: "India" },
      "Indonesia": { language: "id", currency: "IDR", country: "Indonesia" },
      "Iran": { language: "fa", currency: "IRR", country: "Iran" },
      "Iraq": { language: "ar", currency: "IQD", country: "Iraq" },
      "Ireland": { language: "en", currency: "EUR", country: "Ireland" },
      "Israel": { language: "he", currency: "ILS", country: "Israel" },
      "Italy": { language: "it", currency: "EUR", country: "Italy" },
      "Jamaica": { language: "en", currency: "JMD", country: "Jamaica" },
      "Japan": { language: "ja", currency: "JPY", country: "Japan" },
      "Jordan": { language: "ar", currency: "JOD", country: "Jordan" },
      "Kazakhstan": { language: "kk", currency: "KZT", country: "Kazakhstan" },
      "Kenya": { language: "en", currency: "KES", country: "Kenya" },
      "Kuwait": { language: "ar", currency: "KWD", country: "Kuwait" },
      "Latvia": { language: "lv", currency: "EUR", country: "Latvia" },
      "Lebanon": { language: "ar", currency: "LBP", country: "Lebanon" },
      "Libya": { language: "ar", currency: "LYD", country: "Libya" },
      "Lithuania": { language: "lt", currency: "EUR", country: "Lithuania" },
      "Luxembourg": { language: "fr", currency: "EUR", country: "Luxembourg" },
      "Madagascar": { language: "mg", currency: "MGA", country: "Madagascar" },
      "Malaysia": { language: "ms", currency: "MYR", country: "Malaysia" },
      "Malta": { language: "mt", currency: "EUR", country: "Malta" },
      "Mexico": { language: "es", currency: "MXN", country: "Mexico" },
      "Moldova": { language: "ro", currency: "MDL", country: "Moldova" },
      "Mongolia": { language: "mn", currency: "MNT", country: "Mongolia" },
      "Montenegro": { language: "sr", currency: "EUR", country: "Montenegro" },
      "Morocco": { language: "ar", currency: "MAD", country: "Morocco" },
      "Myanmar": { language: "my", currency: "MMK", country: "Myanmar" },
      "Nepal": { language: "ne", currency: "NPR", country: "Nepal" },
      "Netherlands": { language: "nl", currency: "EUR", country: "Netherlands" },
      "New Zealand": { language: "en", currency: "NZD", country: "New Zealand" },
      "Nicaragua": { language: "es", currency: "NIO", country: "Nicaragua" },
      "Nigeria": { language: "en", currency: "NGN", country: "Nigeria" },
      "North Korea": { language: "ko", currency: "KPW", country: "North Korea" },
      "North Macedonia": { language: "mk", currency: "MKD", country: "North Macedonia" },
      "Norway": { language: "no", currency: "NOK", country: "Norway" },
      "Oman": { language: "ar", currency: "OMR", country: "Oman" },
      "Pakistan": { language: "en", currency: "PKR", country: "Pakistan" },
      "Panama": { language: "es", currency: "PAB", country: "Panama" },
      "Paraguay": { language: "es", currency: "PYG", country: "Paraguay" },
      "Peru": { language: "es", currency: "PEN", country: "Peru" },
      "Philippines": { language: "en", currency: "PHP", country: "Philippines" },
      "Poland": { language: "pl", currency: "PLN", country: "Poland" },
      "Portugal": { language: "pt", currency: "EUR", country: "Portugal" },
      "Qatar": { language: "ar", currency: "QAR", country: "Qatar" },
      "Romania": { language: "ro", currency: "RON", country: "Romania" },
      "Russia": { language: "ru", currency: "RUB", country: "Russia" },
      "Saudi Arabia": { language: "ar", currency: "SAR", country: "Saudi Arabia" },
      "Serbia": { language: "sr", currency: "RSD", country: "Serbia" },
      "Singapore": { language: "en", currency: "SGD", country: "Singapore" },
      "Slovakia": { language: "sk", currency: "EUR", country: "Slovakia" },
      "Slovenia": { language: "sl", currency: "EUR", country: "Slovenia" },
      "South Africa": { language: "en", currency: "ZAR", country: "South Africa" },
      "South Korea": { language: "ko", currency: "KRW", country: "South Korea" },
      "Spain": { language: "es", currency: "EUR", country: "Spain" },
      "Sri Lanka": { language: "si", currency: "LKR", country: "Sri Lanka" },
      "Sudan": { language: "ar", currency: "SDG", country: "Sudan" },
      "Sweden": { language: "sv", currency: "SEK", country: "Sweden" },
      "Switzerland": { language: "de", currency: "CHF", country: "Switzerland" },
      "Syria": { language: "ar", currency: "SYP", country: "Syria" },
      "Taiwan": { language: "zh", currency: "TWD", country: "Taiwan" },
      "Tanzania": { language: "sw", currency: "TZS", country: "Tanzania" },
      "Thailand": { language: "th", currency: "THB", country: "Thailand" },
      "Tunisia": { language: "ar", currency: "TND", country: "Tunisia" },
      "Turkey": { language: "tr", currency: "TRY", country: "Turkey" },
      "Uganda": { language: "en", currency: "UGX", country: "Uganda" },
      "Ukraine": { language: "uk", currency: "UAH", country: "Ukraine" },
      "United Arab Emirates": { language: "ar", currency: "AED", country: "United Arab Emirates" },
      "United Kingdom": { language: "en", currency: "GBP", country: "United Kingdom" },
      "United States": { language: "en", currency: "USD", country: "United States" },
      "Uruguay": { language: "es", currency: "UYU", country: "Uruguay" },
      "Uzbekistan": { language: "uz", currency: "UZS", country: "Uzbekistan" },
      "Venezuela": { language: "es", currency: "VES", country: "Venezuela" },
      "Vietnam": { language: "vi", currency: "VND", country: "Vietnam" },
      "Yemen": { language: "ar", currency: "YER", country: "Yemen" },
      "Zambia": { language: "en", currency: "ZMW", country: "Zambia" },
      "Zimbabwe": { language: "en", currency: "ZWL", country: "Zimbabwe" }
    };
    
    return countryPreferences[countryName] || defaults;
  }
  